### ISSUE TITLE
Revisar e concluir o documento de Visão

### ISSUE THREAD

**Issue by kilaG** [kilaG/CadastroAtletas#1]
solicito a equipe ler e se necessário corrigir o documento de visão do projeto.

**Comment by vitorguimars** [comment]
pessoal da uma verificada .... dei uma atualizada no documento vision.... verifiquem se alterou o documento para vcs... aqui para mim alterou, uma outra coisa, faltou definir o nome da empresa, eu deixei como System Information, se alguém tiver alguma sugestão melhor, outra coisa temos que definir o nome do projeto Sugestões????? .

**Comment by vitorguimars** [comment]
Após o OK de vcs eu fecho o ticket ;)

**Comment by kilaG** [comment]
pra mim ok

**Comment by vitorguimars** [comment]
Fechando o ticket..

**Comment by kilaG** [comment]
tem um erro no unlike, tem que descrever um produto semelhante ao nosso (sistema de gestao esportiva por exemplo) tem como arrumar isso @vitorguimars ?

**Comment by kilaG** [comment]
vo tenta faze aqui tenho q configurar o git na minha maquina pessoal

**Comment by kilaG** [comment]
pronto
