### ISSUE TITLE
Configurar ambientes nos computadores

### ISSUE THREAD

**Issue by kilaG** [kilaG/CadastroAtletas#2]
@vitorguimars 
@tfigueiro
@kilaG 
instalar e configurar gitbash.

@brunoribs
resolver problemas com a equipe de suporte do github

**Comment by kilaG** [comment]
instalado e configurado.

**Comment by tfigueiro** [comment]
Configurado!

Criado Wiki com alguns passos para a configuração do Gitbash no Senac

**Comment by vitorguimars** [comment]
Configurado!

**Comment by brunoribs** [comment]
Problema Resolvido
