### ISSUE TITLE
Unificar modelo e implementação

### ISSUE THREAD

**Issue by masmangan** [kilaG/CadastroAtletas#28]
Criar projeto paralelo (fork).

Copiar código gerado para o projeto do NetBeans (Entidades).
Realizar engenharia reversa das classes implementadas (form e java).
Organizar nomes de pacotes no NetBeans e no Modelo.

Atualizar .astah e projeto do Netbeans.

**Comment by vitorguimars** [comment]
Realizado Tarefa..
