### ISSUE TITLE
Criar modelo de caso de uso 

### ISSUE THREAD

**Issue by tfigueiro** [kilaG/CadastroAtletas#3]
criar o modelo no astah...

dependente da Issue #1

**Comment by kilaG** [comment]
Vou fazer agora....

**Comment by kilaG** [comment]
Feito, aguardo aprovação para fechar a issue.

**Comment by vitorguimars** [comment]
Por mim  ta legal... Pode fechar...

**Comment by vitorguimars** [comment]
Mas tem que ter outro caso de uso para o cenário "Gerar Time".

**Comment by brunoribs** [comment]
tem mas vai ser feito depois, vamos dar prioridade ao gerar time.
