### ISSUE TITLE
Criar a especificação do primeiro caso de uso

### ISSUE THREAD

**Issue by kilaG** [kilaG/CadastroAtletas#4]
@brunoribs  @vitorguimars  @tfigueiro 

depois que a issue #3 estiver resolvida devemos chegar a um consenso de qual caso de uso do modelo vamos escolher.

**Comment by kilaG** [comment]
@vitorguimars 
favor dar continuidade ao documento Especificação de Caso de Uso: Gerar Time ... é só seguir o exemplo qualquer coisa grita...

**Comment by vitorguimars** [comment]
Ja realizado atualização da especificação de caso de uso Gerar Time
